logging:
  level:
    root: info
    com.project.pickaboo: debug

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:C:/devpets/pickaboo
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true

# JWT
  security:
    jwt:
      token:
        secret-key: cxo62hCMz3BN+UuvPYB9OY2L0ZAcYcUGYm5QCAITzpc=
        access-token-expire-length: 3600000
        refresh-token-expire-length: 604800000